name: sane_flog
description: Flutter package that allows for ndjson logging for apps.
version: 0.0.4
homepage: https://github.com/psiayn/sane_flog

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.4
  mongo_dart: ^0.7.3
